### ISSUE TITLE
Use with JSDOM v14?

### ISSUE THREAD

**Issue by felixfbecker** [simon360/jest-environment-jsdom-global#14]
Unfortunately I cannot use both this _and_ https://github.com/ianschmitz/jest-environment-jsdom-fourteen. Any idea for a solution?

**Comment by heygrady** [comment]
I created a file named `jest-environment-jsdom-fourteen-global.js` and used that as my test environment.

```json
"testEnvironment": "<rootDir>/jest-environment-jsdom-fourteen-global.js",
```

```js
// https://github.com/simon360/jest-environment-jsdom-global
// https://github.com/ianschmitz/jest-environment-jsdom-fourteen
const JSDOMEnvironment = require('jest-environment-jsdom-fourteen')

module.exports = class JSDOMEnvironmentGlobal extends JSDOMEnvironment {
  constructor(config) {
    super(config)
    this.global.jsdom = this.dom
  }

  teardown() {
    this.global.jsdom = null

    return super.teardown()
  }
}

```

**Comment by simon360** [comment]
Thanks both.

If this becomes a common request, I may add this solution to the documentation, but for now, I'm going to close this as a wontfix.

**Comment by paulchaplin** [comment]
For what it's worth, I just encountered a need for this when trying to mix-and-match with `jest-environment-jsdom-sixteen`, but received this error:

`TypeError: Cannot read property 'console' of undefined`

It turned out to be because the constructor in `jest-environment-jsdom-sixteen` expected a _second argument_, `options`, which Jest passes. This worked for me:

```js
// Custom jest-environment.js file
const JSDOMEnvironment = require("jest-environment-jsdom-sixteen");

module.exports = class JSDOMEnvironmentGlobal extends JSDOMEnvironment {
    constructor(config, options) {
        super(config, options);

        this.global.jsdom = this.dom;
    }

    teardown() {
        this.global.jsdom = null;

        return super.teardown();
    }
};
```

Maybe worth adding something to the documentation, with a caveat, @simon360? And thanks for this package as a template!

**Comment by simon360** [comment]
Aha, interesting! Looks like there's an `options` argument in `jest-environment-jsdom` now, too. (Not sure if it was there before and I missed it, or if it was added after I initially published this package.)

I've got a bit of time on my hands, thanks to... _current world affairs_. So I may have a look at making `jest-environment-jsdom-sixteen` work out of the box.

**Comment by simon360** [comment]
@paulchaplin if you're interested, this package supports `jest-environment-jsdom-sixteen` out of the box (with a fallback to `jest-environment-jsdom`, if it's not found).
