### ISSUE TITLE
Can I use this to mock localStorage?

### ISSUE THREAD

**Issue by wallzero** [simon360/jest-environment-jsdom-global#18]
I am trying to use this to mock localStorage:

```ts
const localStorage = {
  getItem: jest.fn().mockReturnValue(JSON.stringify({
    BUILD_DATE: DATE
  }))
};

jsdom.reconfigure({
  localStorage
});
```

However it doesn't appear to work. Is mocking localStorage with `jest-environment-jsdom-global` possible?

**Comment by simon360** [comment]
Hi @wallzero! Sorry for the late response. Seems like I misconfigured my email notifications for this repo.

It's totally possible to mock `localStorage` with this library, but it is with Jest on its own, too. Just do something like:

```js
beforeEach(() => {
  Object.defineProperty(window, 'localStorage', {
    value: {
      getItem: jest.fn(() => 'result'),
    }
  });
});

it('should use the mocked local storage', () => {
  expect(window.localStorage.getItem('test')).toBe('result');
  expect(window.localStorage.getItem).toHaveBeenCalledTimes(1);
});
```

You can see this at work here: https://repl.it/repls/BuzzingIdioticSoftwaresuite
