### ISSUE TITLE
Add support for Jest 26

### ISSUE THREAD

**Issue by kaiyoma** [simon360/jest-environment-jsdom-global#35]
Jest 26 is out, which means installing this package results in this kind of warning:

```
warning " > jest-environment-jsdom-global@2.0.2" has incorrect peer dependency "jest-environment-jsdom@22.x || 23.x || 24.x || 25.x".
```

**Comment by simon360** [comment]
Thanks for the report, @kaiyoma. I've jsut released `v2.0.3`, which should remove the warning.
