### ISSUE TITLE
TypeError: _jestEnvironmentJsdomGlobal.default.reconfigure is not a function

### ISSUE THREAD

**Issue by gicontz** [simon360/jest-environment-jsdom-global#40]
I've tried:

```typescript
import * as jsdom from 'jest-environment-jsdom-global';
```
and 
```typescript
import jsdom from 'jest-environment-jsdom-global';
```

Code Excerpt:
```typescript
import * as isActive from './activity-functions';
import jsdom from 'jest-environment-jsdom-global';

describe('activity functions', () => {
  it('verifies that the navbar is always active', () => {
    jsdom.reconfigure({
      url: "https://localhost/navbar",
    });
......
```

Package.json
```json
    ....
    "jest": "^25.2.7",
    "jest-cli": "^25.2.7",
    "jest-environment-jsdom": "^26.1.0",
    "jest-environment-jsdom-global": "^2.0.4",
    "lint-staged": "^10.2.7",
    "prettier": "^2.0.5",
     ...
```

Jest Config
```json
  "jest": {
    "testEnvironment": "jest-environment-jsdom-global",
    "coverageReporters": [
      "text",
      "text-summary"
    ]
  }
```

Error:
```
activity functions › verifies that the navbar is always active

    TypeError: _jestEnvironmentJsdomGlobal.default.reconfigure is not a function

      4 | describe('activity functions', () => {
      5 |   it('verifies that the navbar is always active', () => {
    > 6 |     jsdom.reconfigure({
        |           ^
```

**Comment by cihangir-mercan** [comment]
> I've tried:
> 
> ```ts
> import * as jsdom from 'jest-environment-jsdom-global';
> ```
> 
> and
> 
> ```ts
> import jsdom from 'jest-environment-jsdom-global';
> ```
> 
> Code Excerpt:
> 
> ```ts
> import * as isActive from './activity-functions';
> import jsdom from 'jest-environment-jsdom-global';
> 
> describe('activity functions', () => {
>   it('verifies that the navbar is always active', () => {
>     jsdom.reconfigure({
>       url: "https://localhost/navbar",
>     });
> ......
> ```
> 
> Package.json
> 
> ```json
>     ....
>     "jest": "^25.2.7",
>     "jest-cli": "^25.2.7",
>     "jest-environment-jsdom": "^26.1.0",
>     "jest-environment-jsdom-global": "^2.0.4",
>     "lint-staged": "^10.2.7",
>     "prettier": "^2.0.5",
>      ...
> ```
> 
> Jest Config
> 
> ```json
>   "jest": {
>     "testEnvironment": "jest-environment-jsdom-global",
>     "coverageReporters": [
>       "text",
>       "text-summary"
>     ]
>   }
> ```
> 
> Error:
> 
> ```
> activity functions › verifies that the navbar is always active
> 
>     TypeError: _jestEnvironmentJsdomGlobal.default.reconfigure is not a function
> 
>       4 | describe('activity functions', () => {
>       5 |   it('verifies that the navbar is always active', () => {
>     > 6 |     jsdom.reconfigure({
>         |           ^
> ```

did you solve the issue?

**Comment by cihangir-mercan** [comment]
did you solve the issue?

**Comment by simon360** [comment]
For anyone encountering this in the future: `jsdom` is a global. You don't need to import it at all—and if you try to, you'll get errors.

I'd much prefer if `jsdom` was imported, but the Jest environment API makes that a bit difficult. The idea of an "environment" is that it configures globals—such as `window`—to simulate a real-world environment (in this case, a browser).

Exposing `jsdom` in this way is a bit counter to that idea, but (at least, at the time this environment was written) there was no better way to access some occasionally-useful `jsdom` methods. So, `jsdom` is a global when you're using this environment.
