### ISSUE TITLE
Object.defineProperty , work around for href writable

### ISSUE THREAD

**Issue by abhijeetNmishra** [simon360/jest-environment-jsdom-global#6]
Documentation of this repo talk about setting the URL at a specific value, can we also talk about what is the work around for 

```javascript
Object.defineProperty(window.location, 'href', {
        writable: true
      });
```

Few more examples related to general use cases will be very helpful for folks upgrading to Jest 22 and running into JSDOM 11 issues

**Comment by abhijeetNmishra** [comment]
@simon360 my understanding of JSOM use cases is not super great.

**Comment by simon360** [comment]
(Cross linking to facebook/jest#5124 for continuity.)

@abhijeetNmishra I'm not totally clear on what you're asking for. Are you trying to change the value of `window.location.href` from inside your test suite, or from inside your test subject?

**Comment by abhijeetNmishra** [comment]
@simon360 the function I am testing is trying to set value on `window.location.href` and test is actually `expect(window.location.href).toEqual(expected);` with Jest 21 , 

```javascript 
Object.defineProperty(window.location, 'href', {
        writable: true
      });
``` works fine. but with Jest 22 its not working.

**Comment by abhijeetNmishra** [comment]
even with using `window.location.assign`, I get the value for window.location.href to be `"about:blank"` and not the value which I am setting.

**Comment by simon360** [comment]
@abhijeetNmishra again, I'm not sure, as I haven't had to use this particular method, but I suspect you could use a `jest.fn()` mock on `window.location.assign`, and test that `assign()` was called with the expected value.

**Comment by ugultopu** [comment]
> you could use a `jest.fn()` mock on `window.location.assign`

How would you do this? Could you provide a MRE?

**Comment by simon360** [comment]
@ugultopu Sorry, I won't be able to help you there—I don't use this library anymore, though I continue to maintain it.

I suspect you'll be better off asking elsewhere, as this issue has been closed for some time.
