### ISSUE TITLE
Do I need to eject?

### ISSUE THREAD

**Issue by QuantumInformation** [simon360/jest-environment-jsdom-global#8]
![image](https://user-images.githubusercontent.com/216566/45432313-785ab300-b6a1-11e8-821a-19790bc4a5b9.png)

**Comment by simon360** [comment]
This question would be better suited for the [CRA repo](
https://github.com/facebook/create-react-app) - but I suspect that, yes, you would need to eject.

**Comment by QuantumInformation** [comment]
What should I specifically ask for?
